<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Yoke_Input_Scaling" Id="{f2a70c25-57f1-440e-bbb9-1cf149bd7ad5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Yoke_Input_Scaling
VAR_INPUT
	bEnable : BOOL;
	nRawInput : INT; 
	stYokeInputScaling : ST_Yoke_Input_Scaling; 
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>